package main.java.raf.dsw.classycraft.app.model.observer.notifications;

public enum SystemEvent {
    NODE_CANNOT_BE_DELETED,
    NODE_CANNOT_BE_DUPLICATE,
    NAME_CANNOT_BE_EMPTY,
    CANNOT_REMOVE_ROOT,
    DIAGRAM_CAN_ONLY_BE_ADDED_TO_PACKAGE,
    CANNOT_ADD_PACKAGE_TO_ROOT_OR_DIAGRAM,
    CHANGE_AUTHOR_CAN_ONLY_BE_PREFORMED_ON_PROJECTS,
}
