package main.java.raf.dsw.classycraft.app.model.message;

public enum SystemEvent {
    NODE_CANNOT_BE_DELETED,
    NODE_CANNOT_BE_DUPLICATE,
    NAME_CANNOT_BE_EMPTY,
    CANNOT_REMOVE_ROOT,
    CANNOT_ADD_DIAGRAM_TO_ROOT_OR_DIAGRAM,
    CANNOT_ADD_PACKAGE_TO_ROOT_OR_DIAGRAM, NODE_SELECTED,
}
