package main.java.raf.dsw.classycraft.app.model.message;

public enum SystemEvent {
    //TODO SVI MOGUCI SYS EVENTOVI I ERROR DODATI AN AKRAJu
    NODE_CANNOT_BE_DELETED,
    NODE_CANNOT_BE_DUPLICATE,
    NAME_CANNOT_BE_EMPTY,
    CANNOT_REMOVE_ROOT,
    CANNOT_ADD_DIAGRAM_TO_ROOT_OR_DIAGRAM,
    CANNOT_ADD_PACKAGE_TO_ROOT_OR_DIAGRAM,
    CHANGE_AUTHOR_CAN_ONLY_BE_PREFORMED_ON_PROJECTS,
}
